# Generated by Django 3.2.5 on 2021-07-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('ingredient_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.ingredient')),
                ('menu_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='customer.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=15)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe_quantity',
            field=models.ManyToManyField(through='restaurant.Recipe', to='customer.MenuItem'),
        ),
    ]
